//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pms_alpha1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Internal_FK_Definition_Storage
    {
        public int ID { get; set; }
        public string FK_Name { get; set; }
        public string FK_CreationStatement { get; set; }
        public string FK_DestructionStatement { get; set; }
        public string Table_TruncationStatement { get; set; }
    }
}
