//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pms_alpha1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class somyatrans_pmsDBContext : DbContext
    {
        public somyatrans_pmsDBContext()
            : base("name=somyatrans_pmsDBContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TBL_Client> TBL_Client { get; set; }
        public virtual DbSet<TBL_ClientPM> TBL_ClientPM { get; set; }
        public virtual DbSet<TBL_M_City> TBL_M_City { get; set; }
        public virtual DbSet<TBL_M_Country> TBL_M_Country { get; set; }
        public virtual DbSet<TBL_M_Currency> TBL_M_Currency { get; set; }
        public virtual DbSet<TBL_M_DeliverStatus> TBL_M_DeliverStatus { get; set; }
        public virtual DbSet<TBL_M_Designation> TBL_M_Designation { get; set; }
        public virtual DbSet<TBL_M_Domain> TBL_M_Domain { get; set; }
        public virtual DbSet<TBL_M_Expertise> TBL_M_Expertise { get; set; }
        public virtual DbSet<TBL_M_Language> TBL_M_Language { get; set; }
        public virtual DbSet<TBL_M_ModeOfPayment> TBL_M_ModeOfPayment { get; set; }
        public virtual DbSet<TBL_M_OnTimeDeliverStatus> TBL_M_OnTimeDeliverStatus { get; set; }
        public virtual DbSet<TBL_M_ProcessStatus> TBL_M_ProcessStatus { get; set; }
        public virtual DbSet<TBL_M_Role> TBL_M_Role { get; set; }
        public virtual DbSet<TBL_M_Services> TBL_M_Services { get; set; }
        public virtual DbSet<TBL_M_Software> TBL_M_Software { get; set; }
        public virtual DbSet<TBL_M_State> TBL_M_State { get; set; }
        public virtual DbSet<TBL_M_TaskType> TBL_M_TaskType { get; set; }
        public virtual DbSet<TBL_M_Unit> TBL_M_Unit { get; set; }
        public virtual DbSet<TBL_M_WorkStatus> TBL_M_WorkStatus { get; set; }
        public virtual DbSet<TBL_Project> TBL_Project { get; set; }
        public virtual DbSet<TBL_ProjectTask> TBL_ProjectTask { get; set; }
        public virtual DbSet<TBL_TrackerPC> TBL_TrackerPC { get; set; }
        public virtual DbSet<TBL_TrackerPM> TBL_TrackerPM { get; set; }
        public virtual DbSet<TBL_TrackerSPC> TBL_TrackerSPC { get; set; }
        public virtual DbSet<TBL_Vendor> TBL_Vendor { get; set; }
        public virtual DbSet<TBL_VendorLanguagePair> TBL_VendorLanguagePair { get; set; }
        public virtual DbSet<TBL_VendorService> TBL_VendorService { get; set; }
        public virtual DbSet<TBL_M_Academics> TBL_M_Academics { get; set; }
        public virtual DbSet<TBL_VendorDomain> TBL_VendorDomain { get; set; }
        public virtual DbSet<TBL_VendorSoftware> TBL_VendorSoftware { get; set; }
        public virtual DbSet<Internal_FK_Definition_Storage> Internal_FK_Definition_Storage { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
