//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pms_alpha1
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_VenderSoftware
    {
        public long VenderSoftwareID { get; set; }
        public Nullable<int> VendorID { get; set; }
        public Nullable<int> SoftwareID { get; set; }
        public string Version { get; set; }
        public Nullable<int> ExpertiseID { get; set; }
        public Nullable<bool> Status { get; set; }
    
        public virtual TBL_M_Expertise TBL_M_Expertise { get; set; }
        public virtual TBL_M_Software TBL_M_Software { get; set; }
        public virtual TBL_Vendor TBL_Vendor { get; set; }
    }
}
