//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pms_alpha1
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_M_State
    {
        public TBL_M_State()
        {
            this.TBL_M_City = new HashSet<TBL_M_City>();
            this.TBL_Vendor = new HashSet<TBL_Vendor>();
        }
    
        public int StateID { get; set; }
        public int CountryID { get; set; }
        public string State { get; set; }
        public bool Status { get; set; }
    
        public virtual ICollection<TBL_M_City> TBL_M_City { get; set; }
        public virtual TBL_M_Country TBL_M_Country { get; set; }
        public virtual ICollection<TBL_Vendor> TBL_Vendor { get; set; }
    }
}
