//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pms_alpha1
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_VendorLanguagePair
    {
        public long VendorLanguagePairID { get; set; }
        public Nullable<int> VendorID { get; set; }
        public Nullable<int> SourceLanguageID { get; set; }
        public Nullable<int> TargetLanguageID { get; set; }
        public Nullable<bool> Status { get; set; }
    
        public virtual TBL_M_Language TBL_M_Language { get; set; }
        public virtual TBL_M_Language TBL_M_Language1 { get; set; }
        public virtual TBL_Vendor TBL_Vendor { get; set; }
    }
}
