//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pms_alpha1
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_M_Country
    {
        public TBL_M_Country()
        {
            this.TBL_M_State = new HashSet<TBL_M_State>();
            this.TBL_Vendor = new HashSet<TBL_Vendor>();
        }
    
        public int CountryID { get; set; }
        public string Country { get; set; }
        public bool Status { get; set; }
    
        public virtual ICollection<TBL_M_State> TBL_M_State { get; set; }
        public virtual ICollection<TBL_Vendor> TBL_Vendor { get; set; }
    }
}
