//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pms_alpha1
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_M_Software
    {
        public TBL_M_Software()
        {
            this.TBL_VenderSoftware = new HashSet<TBL_VenderSoftware>();
        }
    
        public int SoftwareID { get; set; }
        public string Software { get; set; }
        public bool Staus { get; set; }
    
        public virtual ICollection<TBL_VenderSoftware> TBL_VenderSoftware { get; set; }
    }
}
