//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pms_alpha1
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_M_WorkStatus
    {
        public TBL_M_WorkStatus()
        {
            this.TBL_ProjectTask = new HashSet<TBL_ProjectTask>();
            this.TBL_TrackerPC = new HashSet<TBL_TrackerPC>();
            this.TBL_TrackerPM = new HashSet<TBL_TrackerPM>();
            this.TBL_TrackerSPC = new HashSet<TBL_TrackerSPC>();
        }
    
        public int WorkStatusID { get; set; }
        public string WorkStatus { get; set; }
        public bool Status { get; set; }
    
        public virtual ICollection<TBL_ProjectTask> TBL_ProjectTask { get; set; }
        public virtual ICollection<TBL_TrackerPC> TBL_TrackerPC { get; set; }
        public virtual ICollection<TBL_TrackerPM> TBL_TrackerPM { get; set; }
        public virtual ICollection<TBL_TrackerSPC> TBL_TrackerSPC { get; set; }
    }
}
