//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pms_alpha1
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_Project
    {
        public TBL_Project()
        {
            this.TBL_ProjectTask = new HashSet<TBL_ProjectTask>();
            this.TBL_TrackerPC = new HashSet<TBL_TrackerPC>();
            this.TBL_TrackerPM = new HashSet<TBL_TrackerPM>();
            this.TBL_TrackerSPC = new HashSet<TBL_TrackerSPC>();
        }
    
        public long ProjectID { get; set; }
        public string ProjectCode { get; set; }
        public Nullable<int> ClientID { get; set; }
        public Nullable<int> ClientPMID { get; set; }
        public string ProjectName { get; set; }
        public string ProjectDescription { get; set; }
        public Nullable<bool> Status { get; set; }
    
        public virtual TBL_Client TBL_Client { get; set; }
        public virtual TBL_ClientPM TBL_ClientPM { get; set; }
        public virtual ICollection<TBL_ProjectTask> TBL_ProjectTask { get; set; }
        public virtual ICollection<TBL_TrackerPC> TBL_TrackerPC { get; set; }
        public virtual ICollection<TBL_TrackerPM> TBL_TrackerPM { get; set; }
        public virtual ICollection<TBL_TrackerSPC> TBL_TrackerSPC { get; set; }
    }
}
