//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pms_alpha1
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_Client
    {
        public TBL_Client()
        {
            this.TBL_ClientPM = new HashSet<TBL_ClientPM>();
            this.TBL_Project = new HashSet<TBL_Project>();
        }
    
        public int ClientID { get; set; }
        public string Client { get; set; }
        public string Email { get; set; }
        public string AlternetEmail { get; set; }
        public string LandlineNo { get; set; }
        public string MobileNo { get; set; }
        public string SkypeID { get; set; }
        public string Address { get; set; }
        public int CityID { get; set; }
        public int StateID { get; set; }
        public int CountryID { get; set; }
        public string ZipCode { get; set; }
        public int PaymentModeID { get; set; }
        public bool Status { get; set; }
    
        public virtual ICollection<TBL_ClientPM> TBL_ClientPM { get; set; }
        public virtual ICollection<TBL_Project> TBL_Project { get; set; }
    }
}
