//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pms_alpha1
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_ProjectTask
    {
        public long ProjectTaskID { get; set; }
        public Nullable<long> ProjectID { get; set; }
        public Nullable<long> TaskTypeID { get; set; }
        public Nullable<int> SourceLanguageID { get; set; }
        public Nullable<int> TargetLanguageID { get; set; }
        public Nullable<int> UnitID { get; set; }
        public Nullable<int> Volume { get; set; }
        public Nullable<System.DateTime> RecievedDate { get; set; }
        public Nullable<System.DateTime> DeadlineDate { get; set; }
        public Nullable<int> WorkStatusID { get; set; }
        public Nullable<int> ProcessStatusID { get; set; }
        public Nullable<int> DeliverStatusID { get; set; }
        public Nullable<int> OnTimeDeliverStatusID { get; set; }
        public string EndRemarks { get; set; }
        public Nullable<bool> Status { get; set; }
    
        public virtual TBL_M_DeliverStatus TBL_M_DeliverStatus { get; set; }
        public virtual TBL_M_Language TBL_M_Language { get; set; }
        public virtual TBL_M_Language TBL_M_Language1 { get; set; }
        public virtual TBL_M_OnTimeDeliverStatus TBL_M_OnTimeDeliverStatus { get; set; }
        public virtual TBL_M_ProcessStatus TBL_M_ProcessStatus { get; set; }
        public virtual TBL_M_TaskType TBL_M_TaskType { get; set; }
        public virtual TBL_M_Unit TBL_M_Unit { get; set; }
        public virtual TBL_M_WorkStatus TBL_M_WorkStatus { get; set; }
        public virtual TBL_Project TBL_Project { get; set; }
    }
}
