//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pms_alpha1
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_M_Domain
    {
        public TBL_M_Domain()
        {
            this.TBL_Vendor = new HashSet<TBL_Vendor>();
        }
    
        public int DomainID { get; set; }
        public string Domain { get; set; }
        public bool Staus { get; set; }
    
        public virtual ICollection<TBL_Vendor> TBL_Vendor { get; set; }
    }
}
