//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pms_alpha1
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_M_Services
    {
        public TBL_M_Services()
        {
            this.TBL_VendorService = new HashSet<TBL_VendorService>();
        }
    
        public int ServicesID { get; set; }
        public string Services { get; set; }
        public bool Staus { get; set; }
    
        public virtual ICollection<TBL_VendorService> TBL_VendorService { get; set; }
    }
}
