//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pms_alpha1
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_M_Currency
    {
        public TBL_M_Currency()
        {
            this.TBL_VendorService = new HashSet<TBL_VendorService>();
            this.TBL_VendorService1 = new HashSet<TBL_VendorService>();
        }
    
        public int CurrencyID { get; set; }
        public string Currency { get; set; }
        public bool Status { get; set; }
    
        public virtual ICollection<TBL_VendorService> TBL_VendorService { get; set; }
        public virtual ICollection<TBL_VendorService> TBL_VendorService1 { get; set; }
    }
}
