//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pms_alpha1
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_VendorService
    {
        public long VendorServiceID { get; set; }
        public Nullable<int> VendorID { get; set; }
        public Nullable<int> ServiceID { get; set; }
        public Nullable<int> QuotedCurrencyID { get; set; }
        public Nullable<decimal> QuotedRate { get; set; }
        public Nullable<int> FreezedCurrenyID { get; set; }
        public Nullable<decimal> FreezedRate { get; set; }
        public Nullable<bool> Status { get; set; }
    
        public virtual TBL_M_Currency TBL_M_Currency { get; set; }
        public virtual TBL_M_Currency TBL_M_Currency1 { get; set; }
        public virtual TBL_M_Services TBL_M_Services { get; set; }
        public virtual TBL_Vendor TBL_Vendor { get; set; }
    }
}
