//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pms_alpha1
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_TrackerSPC
    {
        public long TrackerSPCID { get; set; }
        public Nullable<long> ProjectID { get; set; }
        public Nullable<System.DateTime> HOTimeSPC { get; set; }
        public Nullable<System.DateTime> HBTimeSPC { get; set; }
        public Nullable<System.DateTime> HBRTimeSPC { get; set; }
        public Nullable<System.DateTime> HBDTimeSPC { get; set; }
        public Nullable<int> WorkStatusID { get; set; }
        public Nullable<int> AssignedTo { get; set; }
        public Nullable<int> VendorID { get; set; }
        public Nullable<int> POID { get; set; }
        public string Remarks { get; set; }
    
        public virtual TBL_M_WorkStatus TBL_M_WorkStatus { get; set; }
        public virtual TBL_Project TBL_Project { get; set; }
        public virtual TBL_Vendor TBL_Vendor { get; set; }
    }
}
