//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pms_alpha1
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_Vendor
    {
        public TBL_Vendor()
        {
            this.TBL_TrackerPC = new HashSet<TBL_TrackerPC>();
            this.TBL_TrackerSPC = new HashSet<TBL_TrackerSPC>();
            this.TBL_VenderSoftware = new HashSet<TBL_VenderSoftware>();
            this.TBL_VendorLanguagePair = new HashSet<TBL_VendorLanguagePair>();
            this.TBL_VendorService = new HashSet<TBL_VendorService>();
        }
    
        public int VendorID { get; set; }
        public string VendorCode { get; set; }
        public string Vendor { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public Nullable<System.DateTime> DateOfAniversary { get; set; }
        public string NativeLanguage { get; set; }
        public string AcademicQualification { get; set; }
        public string ProfessionalQualification { get; set; }
        public string EmailID { get; set; }
        public string AlternateEmailID { get; set; }
        public string SkypeID { get; set; }
        public string ContactNumber { get; set; }
        public string AlternateNumber { get; set; }
        public string Address { get; set; }
        public string HouseNo_StreetNo { get; set; }
        public Nullable<int> CityID { get; set; }
        public Nullable<int> StateID { get; set; }
        public Nullable<int> CountryID { get; set; }
        public string PinCode { get; set; }
        public Nullable<int> DomainID { get; set; }
        public string Capacity { get; set; }
        public Nullable<System.TimeSpan> WorkingTime { get; set; }
        public string RAM { get; set; }
        public string HDD { get; set; }
        public string OS { get; set; }
        public string MSOffice { get; set; }
        public string AnyOtherExprience { get; set; }
        public string TypeofConnection { get; set; }
        public Nullable<decimal> InternetAvailabilityPerDay { get; set; }
        public string InternetServiceProvider { get; set; }
        public string InternetDownTimePerDay { get; set; }
        public string ElectricityDownTimePerDay { get; set; }
        public string AccountHolderName { get; set; }
        public string BankName { get; set; }
        public string BankAddress { get; set; }
        public string AccountNumber { get; set; }
        public string IFSCCode { get; set; }
        public string BranchCode { get; set; }
        public string PanNumber { get; set; }
        public string IBANCode { get; set; }
        public string SWIFTCode { get; set; }
        public string MoneyBookerID { get; set; }
        public string PayPalID { get; set; }
        public Nullable<System.DateTime> RegistrationDate { get; set; }
        public string RegisteredBy { get; set; }
        public string ApprovedBy { get; set; }
        public string UploadPhoto { get; set; }
        public string UploadPersonalID { get; set; }
        public Nullable<bool> Status { get; set; }
    
        public virtual TBL_M_City TBL_M_City { get; set; }
        public virtual TBL_M_Country TBL_M_Country { get; set; }
        public virtual TBL_M_Domain TBL_M_Domain { get; set; }
        public virtual TBL_M_State TBL_M_State { get; set; }
        public virtual ICollection<TBL_TrackerPC> TBL_TrackerPC { get; set; }
        public virtual ICollection<TBL_TrackerSPC> TBL_TrackerSPC { get; set; }
        public virtual ICollection<TBL_VenderSoftware> TBL_VenderSoftware { get; set; }
        public virtual ICollection<TBL_VendorLanguagePair> TBL_VendorLanguagePair { get; set; }
        public virtual ICollection<TBL_VendorService> TBL_VendorService { get; set; }
    }
}
