//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pms_alpha1
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_M_ProcessStatus
    {
        public TBL_M_ProcessStatus()
        {
            this.TBL_ProjectTask = new HashSet<TBL_ProjectTask>();
        }
    
        public int ProcessStatusID { get; set; }
        public string ProcessStatus { get; set; }
        public Nullable<bool> Status { get; set; }
    
        public virtual ICollection<TBL_ProjectTask> TBL_ProjectTask { get; set; }
    }
}
