//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pms_alpha1
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_M_Expertise
    {
        public TBL_M_Expertise()
        {
            this.TBL_VendorSoftware = new HashSet<TBL_VendorSoftware>();
        }
    
        public int ExpertiseID { get; set; }
        public string Expertise { get; set; }
        public bool Staus { get; set; }
    
        public virtual ICollection<TBL_VendorSoftware> TBL_VendorSoftware { get; set; }
    }
}
