//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pms_alpha1
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_TrackerPM
    {
        public long TrackerPMID { get; set; }
        public Nullable<long> ProjectID { get; set; }
        public Nullable<System.DateTime> HOTimePM { get; set; }
        public Nullable<System.DateTime> HBTimePM { get; set; }
        public Nullable<System.DateTime> HBRTimePM { get; set; }
        public Nullable<System.DateTime> HBDTimePM { get; set; }
        public Nullable<int> WorkStatusID { get; set; }
        public Nullable<int> AssignedTo { get; set; }
        public string Remarks { get; set; }
    
        public virtual TBL_M_WorkStatus TBL_M_WorkStatus { get; set; }
        public virtual TBL_Project TBL_Project { get; set; }
    }
}
